--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.107.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 5/13/2023 8:32:10 PM
-- Server version: 15.00.2101
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT linhdgt_electronic.dbo.AspNetUsers(Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, FullName) VALUES (N'8b8818dd-6bd4-4284-b9e4-b046f2623e00', N'dragmedown113@gmail.com', CONVERT(bit, 'False'), N'AM7L2z61SF3IUBTKt4eYuHDBKkScF2+LX3TbOpHqRlhzNg5qWitWnqi+QQYrRir4Ig==', N'5222cf30-6207-4a29-9791-1ea0fecb3851', N'0869143513', CONVERT(bit, 'False'), CONVERT(bit, 'False'), NULL, CONVERT(bit, 'True'), 0, N'admin', N'Lê Quang Linh')
INSERT linhdgt_electronic.dbo.AspNetUsers(Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, FullName) VALUES (N'ac95286c-58b5-4dd3-9dc7-58f355cfad8b', N'heathcliff0704@gmail.com', CONVERT(bit, 'False'), N'AHbClSbfURiaS1xwE4F4dwDD/HkGls48xo/Bdt4j2/pr9PQXJBzPFH32sKhi1KVKkQ==', N'216cceba-9732-47b5-85eb-9443e95421ee', N'123456789', CONVERT(bit, 'False'), CONVERT(bit, 'False'), NULL, CONVERT(bit, 'True'), 0, N'linhmh19kk', N'linh')
INSERT linhdgt_electronic.dbo.AspNetUsers(Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, FullName) VALUES (N'd1c48e26-ca92-410f-9562-d5d80e4bac4e', N'nylklee195@gmail.com', CONVERT(bit, 'False'), N'AJcfe0NL/iVu/VfMXB++poMENl4SmebX7E/IR9txi6cKcLDRgkMnncS5bL6Cu3yEaQ==', N'fa94f721-8d0b-482a-a6c1-6fe58f6b8363', N'0869143513', CONVERT(bit, 'False'), CONVERT(bit, 'False'), NULL, CONVERT(bit, 'True'), 0, N'linhkk01tb', N'Lê Quang Linh')
INSERT linhdgt_electronic.dbo.AspNetUsers(Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, FullName) VALUES (N'f42ba883-72cc-4165-b537-acb352ad91b4', N'heathcliff0701@gmail.com', CONVERT(bit, 'False'), N'AMqRbLp/MHIdXLnldhldUjlVitDwqvwugjHJoEyFmT4b3ej3HzlOSu1fZVKqx4tvig==', N'647848a8-31f0-4801-831b-01325bd8c6a8', NULL, CONVERT(bit, 'False'), CONVERT(bit, 'False'), NULL, CONVERT(bit, 'True'), 0, N'linh12345', NULL)
GO