--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.107.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 5/13/2023 8:31:56 PM
-- Server version: 15.00.2101
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT linhdgt_electronic.dbo.AspNetUserRoles(UserId, RoleId) VALUES (N'8b8818dd-6bd4-4284-b9e4-b046f2623e00', N'925123ce-f3e4-40ff-81c2-2c5d3571ea86')
INSERT linhdgt_electronic.dbo.AspNetUserRoles(UserId, RoleId) VALUES (N'ac95286c-58b5-4dd3-9dc7-58f355cfad8b', N'9d013fac-626b-4c5f-8254-f550aea87fb3')
INSERT linhdgt_electronic.dbo.AspNetUserRoles(UserId, RoleId) VALUES (N'd1c48e26-ca92-410f-9562-d5d80e4bac4e', N'9d013fac-626b-4c5f-8254-f550aea87fb3')
INSERT linhdgt_electronic.dbo.AspNetUserRoles(UserId, RoleId) VALUES (N'f42ba883-72cc-4165-b537-acb352ad91b4', N'9d013fac-626b-4c5f-8254-f550aea87fb3')
GO