--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.107.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 5/13/2023 8:32:54 PM
-- Server version: 15.00.2101
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT linhdgt_electronic.dbo.nhanvien ON
GO
INSERT linhdgt_electronic.dbo.nhanvien(NhanVienID, NhanVienName, NhanVienBirth, NhanVienGender, NhanVienAddress, NhanVienEmail, NhanVienPhoneNumber, NhanVienWorkingDate, NhanVienSalary, NhanVienStatus) VALUES (1, N'Nguyễn Văn Bằng ', '1993-05-17 03:14:52.420', 0, N'số 3 Phùng Khoang', N'DeeannaAbreu59@gmail.com', N'+84 035 802 1232', 24, 245608.52, 1)
INSERT linhdgt_electronic.dbo.nhanvien(NhanVienID, NhanVienName, NhanVienBirth, NhanVienGender, NhanVienAddress, NhanVienEmail, NhanVienPhoneNumber, NhanVienWorkingDate, NhanVienSalary, NhanVienStatus) VALUES (2, N'Mai Tú Tuệ', '1994-07-12 14:50:26.270', 0, N'12 phan bá vành', N'bbzsaxow6411@gmail.com', N'+84 032 712 3938', 8, 250284.43, 1)
INSERT linhdgt_electronic.dbo.nhanvien(NhanVienID, NhanVienName, NhanVienBirth, NhanVienGender, NhanVienAddress, NhanVienEmail, NhanVienPhoneNumber, NhanVienWorkingDate, NhanVienSalary, NhanVienStatus) VALUES (3, N'Hoàng Anh Bình ', '1997-05-25 14:43:14.330', 0, N'5 Quang Trung', N'Chan81@gmail.com', N'+84 037 908 8649', 15, 312934.57, 0)
INSERT linhdgt_electronic.dbo.nhanvien(NhanVienID, NhanVienName, NhanVienBirth, NhanVienGender, NhanVienAddress, NhanVienEmail, NhanVienPhoneNumber, NhanVienWorkingDate, NhanVienSalary, NhanVienStatus) VALUES (4, N'Nguyễn Văn Chung ', '1996-02-17 11:41:07.470', 1, N'số 3 ngách 10 ngõ 122 phố vĩnh tuy', N'Angel8@gmail.com', N'+84 038 907 5096', 16, 266194.56, 0)
INSERT linhdgt_electronic.dbo.nhanvien(NhanVienID, NhanVienName, NhanVienBirth, NhanVienGender, NhanVienAddress, NhanVienEmail, NhanVienPhoneNumber, NhanVienWorkingDate, NhanVienSalary, NhanVienStatus) VALUES (5, N'Trần Văn Chung ', '1996-07-27 04:35:04.090', 0, N'149 ngõ 670 nguyễn khoái', N'Piper_Mattson432@gmail.com', N'+84 037 856 0423', 19, 292100.91, 1)
INSERT linhdgt_electronic.dbo.nhanvien(NhanVienID, NhanVienName, NhanVienBirth, NhanVienGender, NhanVienAddress, NhanVienEmail, NhanVienPhoneNumber, NhanVienWorkingDate, NhanVienSalary, NhanVienStatus) VALUES (6, N'Trần Văn Đức ', '1995-05-11 11:52:22.310', 1, N'33 Phạm Ngũ Lão', N'SilasGeary98@gmail.com', N'+84 036 699 8405', 24, 235314.19, 0)
INSERT linhdgt_electronic.dbo.nhanvien(NhanVienID, NhanVienName, NhanVienBirth, NhanVienGender, NhanVienAddress, NhanVienEmail, NhanVienPhoneNumber, NhanVienWorkingDate, NhanVienSalary, NhanVienStatus) VALUES (7, N'Bùi Hưng Thọ ', '1993-08-23 14:19:00.820', 0, N'697 Vũ Tông Phan', N'Abreu@gmail.com', N'+84 030 831 8700', 24, 294425.33, 1)
GO
SET IDENTITY_INSERT linhdgt_electronic.dbo.nhanvien OFF
GO